version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: ct_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ct_backend
    env_file: [.env]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGINS: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_net
      - frontend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: ct_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - frontend_net

  adminer:
    image: adminer:4
    container_name: ct_adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - backend_net

volumes:
  db_data:

networks:
  backend_net:
  frontend_net:
